[project]
name = "finality-shield"
authors = ["Finality Shield Team"]
description = "A decentralized financial settlement protocol on Stacks"
telemetry = false
requirements = []
[contracts.finality-shield-core]
path = "contracts/finality-shield-core.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
